export default [
  {
    title: 'Dashboard ',
    icon: 'PieChartIcon',
    tagVariant: 'light-warning',
    route: 'dashboard-analytics',
    resource: 'Dashboard',
    action: 'read',
  },
  {
    title: 'Dashboard COD',
    icon: 'HomeIcon',
    tagVariant: 'light-warning',
    route: 'cod-dashboard',
    resource: 'Dashboard',
    action: 'read',
  },
  {
    title: 'Pencairan',
    icon: 'DownloadIcon',
    tagVariant: 'light-warning',
    route: 'cod-pencairan',
    resource: 'Dashboard',
    action: 'read',
  },
  {
    title: 'Pendapatan',
    icon: 'ArchiveIcon',
    tagVariant: 'light-warning',
    route: 'cod-pendapatan',
    resource: 'Dashboard',
    action: 'read',
  },
  {
    title: 'Home',
    icon: 'PieChartIcon',
    tagVariant: 'light-warning',
    route: 'talent-home',
    resource: 'TalentHome',
    action: 'read',
  },
  {
    title: 'Dashboards',
    icon: 'PieChartIcon',
    tagVariant: 'light-warning',
    route: 'partner-home',
    resource: 'PartnerHome',
    action: 'read',
  },
]
