export default [
  {
    title: 'Master Data',
    icon: 'HardDriveIcon',
    tagVariant: 'light-warning',
    children: [
      {
        title: 'Kantor Operational',
        icon: 'LayersIcon',
        route: 'operational-offices',
        resource: 'MasterData',
        action: 'manage',
      },
      {
        title: 'Working Space',
        icon: 'CodepenIcon',
        route: 'work-spaces',
        resource: 'MasterData',
        action: 'manage',
      },
      {
        title: 'Biaya Admin',
        icon: 'UserPlusIcon',
        route: 'admin-fee',
        resource: 'Invoice',
        action: 'manage',
      },
      {
        title: 'Sharing Fee',
        icon: 'DollarSignIcon',
        route: 'sharing-fee',
        resource: 'Invoice',
        action: 'manage',
      },
      {
        title: 'Divisi',
        icon: 'UsersIcon',
        tagVariant: 'light-warning',
        route: 'divisions',
        resource: 'Division',
        action: 'manage',
      },
      {
        title: 'Posisi',
        icon: 'BriefcaseIcon',
        route: 'positions',
        resource: 'Position',
        action: 'manage',
      },
      {
        title: 'Role Akses',
        icon: 'UsersIcon',
        tagVariant: 'light-warning',
        route: 'job-role-setting',
        resource: 'JobRoleSetting',
        action: 'manage',
      },
    ],
  },
]
